### PR TITLE
add JNGL to markets

### PR DESCRIPTION
**Pull request by running0x**
Request to add JNGL options to mainnet markets

### CODE REVIEW

**Comment by Taylor123** [comment]
@running0x Thanks for the PR!! Would you like to include the token information into the `psy-token-registry` package as well? This will make sure it shows up nicely within the UI

**Comment by running0x** [comment]
@Taylor123 oh sorry! Is there any documentation on how to correctly add it there? Adding this market was straight forward I must have missed a step.

**Comment by running0x** [comment]
@Taylor123 sorry nevermind, it's totally straight forward! we should be able to take care of this today, thanks

**Comment by running0x** [comment]
@Taylor123 I think we should be good now, if not lmk - thanks!

**Comment by tomjohn1028** [comment]
@running0x lookin good!

**Pull request merged**
